### ISSUE TITLE
thread 'main' panicked at src/ui.rs:67:70

### ISSUE THREAD

**Issue by muralikodali** [sk8ersteve/audio-select#1]
application is unable to start.

i am attaching rust_backtrace log file.

[fail.log](https://github.com/sk8ersteve/audio-select/files/13743428/fail.log)

**Comment by sudosteve** [comment]
Ooh, I did not expect anyone to use non-ASCII characters in their labels. Will fix.

**Comment by sudosteve** [comment]
@muralikodali are you compiling the code yourself? If so, can you pull the latest commit and test again?

**Comment by muralikodali** [comment]
thanks, updated version is working as expected.

i have installed indic language telugu (in_tel) as second language on my system. pulse audio has picked up this language for ui, without my selection.
